apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: kafka-system
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  restartPolicy: Always
  hostNetwork: true

