apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: cert-manager
spec:
  containers:
  - name: test-container
    image: curlimages/curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']
