---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-http-route
  namespace: kube-system
spec:
  parentRefs:
  - name: http-gateway
    # namespace: kube-system
  # - name: tls-gateway
  #   namespace: kube-system
  hostnames:
  - "hubble-ui.pfs.pack"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: hubble-ui
      port: 80

