---
# services must be annotated with: to be able to share the same lb ip
# By default, sharing IPs across namespaces is not allowed. To allow
# sharing across a namespace, set the
#      lbipam.cilium.io/sharing-cross-namespace annotation to
#      the namespaces the service can be shared with.
# The value must be a comma-separated list of namespaces.
# The annotation must be present on both services.
# You can allow all namespaces with *.
# annotations:
#     lbipam.cilium.io/sharing-key: "1234"
#     lbipam.cilium.io/sharing-cross-namespace: *
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-ips
  annotations:
    lbipam.cilium.io/sharing-key: kafkaCluster
    lbipam.cilium.io/sharing-cross-namespace: default,kube-system
spec:
  blocks:
  - cidr: "10.66.65.7/32"
  # - start: "10.66.65.8"
  #   stop: "10.66.65.9"
  disabled: false
################################################################################
---
# hubble-ui ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-system-ui-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: cilium  # deprecated and replaced by spec.ingressClassName
    ingress.cilium.io/service-external-traffic-policy: Cluster
    ingress.cilium.io/service-type: LoadBalancer
    lbipam.cilium.io/sharing-key: "kafkaCluster"
    lbipam.cilium.io/sharing-cross-namespace: default,kube-system
    lbipam.cilium.io/ips: "10.66.65.7"
    cilium.io/ssl-redirect: 'false'
spec:

  ingressClassName: cilium
  rules:
  - host: hubble-ui.pfs.pack
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: hubble-ui
            port:
              name: http
  - host: longhorn-ui.pfs.pack
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
  # tls:
  # - hosts:
  #   - hubble-ui.pfs.pack
  #   secretName: hubble-cert

  # defaultBackend:
  #   service:
  #     name: default-page-menu
  #     port:
  #       name: http
################################################################################
