apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "loadbalancer-ip-pool"
spec:
  blocks:
  # - cidr: "10.66.65.8/32"
  # - cidr: "10.66.65.9/32"
  - start: "10.66.65.8"
    stop: "10.66.65.9"
  disabled: false

# services must be annotated with: to be able to share the same lb ip
# By default, sharing IPs across namespaces is not allowed. To allow
# sharing across a namespace, set the
#      lbipam.cilium.io/sharing-cross-namespace annotation to
#      the namespaces the service can be shared with.
# The value must be a comma-separated list of namespaces.
# The annotation must be present on both services.
# You can allow all namespaces with *.
# annotations:
#     lbipam.cilium.io/sharing-key: "1234"
#     lbipam.cilium.io/sharing-cross-namespace: *