apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-test-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
  hostPath:
    # path: /opt/kafka/controller
    path: "/mnt/longhorn-1/test"

