---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rancher-ui
  namespace: cattle-system
spec:
  parentRefs:
  - name: tls-gateway
    namespace: kube-system
  hostnames:
  - "rancher.pfs.pack"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rancher
      port: 80
