kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
certificatesDir: /etc/kubernetes/pki
clusterName: ${CLUSTER_NAME}
controlPlaneEndpoint: ${CONTROL_PLANE_NODE}:${CONTROL_PLANE_API_PORT}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: ${KUBE_IMAGE_REPO}
kubernetesVersion: v${K8S_MINOR_VERSION}
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/24"
  dnsDomain: "cluster.local"
# CILIUM REPLACEMENT
proxy:
  disabled: true

apiServer:
  certSANs: ${CONTROL_PLANE_NODES_LIST}
# controllerManager: {}
# dns: {}
# encryptionAlgorithm: RSA-2048