kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
certificatesDir: /etc/kubernetes/pki
clusterName: ${CLUSTER_NAME}
controlPlaneEndpoint: ${CONTROL_PLANE_NODE}:${CONTROL_PLANE_API_PORT}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: ${KUBE_IMAGE_REPO}
kubernetesVersion: v${K8S_MINOR_VERSION}
# networking:
#   dnsDomain: ${CLUSTER_DNS_DOMAINS}
#   serviceSubnet: ${CLUSTER_SERVICES_SUBNET}
# CILIUM REPLACEMENT
proxy:
  disabled: true
certSANs: ${CONTROL_PLANE_NODES_LIST}
# controllerManager: {}
# dns: {}
# encryptionAlgorithm: RSA-2048