---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-http
  namespace: keycloak
spec:
  parentRefs:
  - name: shared-https-gateway
    namespace: kube-system
    sectionName: http
  hostnames:
  - keycloak.pfs.pack
  # rules:
  # - backendRefs:
  #   - name: keycloak
  #     port: 80
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-https-redirect
  namespace: keycloak
spec:
  parentRefs:
  - name: shared-https-gateway
    namespace: kube-system
    sectionName: https
  hostnames:
  - keycloak.pfs.pack
  rules:
  - backendRefs:
    - name: keycloak
      port: 80
