---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brokers-tls-cert
  namespace: strimzi-kafka
spec:
  secretName: brokers-tls-cert
  commonName: brokers-tls-cert
  subject:
    organizations:
    - kafka-brokers
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - kafka-listener.pfs.pack
  - kafka-boostrap.pfs.pack

  - kafka-broker-0.pfs.pack
  - kafka-broker-1.pfs.pack
  - kafka-broker-2.pfs.pack

  - kafka-bootstrap.pfs.pack
  - kafka-cluster-bootstrap.pfs.pack

  - broker-0-kafka-cluster.pfs.pack
  - broker-1-kafka-cluster.pfs.pack
  - broker-2-kafka-cluster.pfs.pack

  - kafka-cluster-broker-a-tls-10
  - kafka-cluster-broker-a-tls-10.svc
  - kafka-cluster-broker-a-tls-10.svc.cluster.local

  - kafka-cluster-broker-b-tls-11
  - kafka-cluster-broker-b-tls-11.svc
  - kafka-cluster-broker-b-tls-11.svc.cluster.local

  - kafka-cluster-broker-c-tls-12
  - kafka-cluster-broker-c-tls-12.svc
  - kafka-cluster-broker-c-tls-12.svc.cluster.local
  ipAddresses:
  - 10.66.65.10
  - 10.66.65.11
  - 10.66.65.12
  issuerRef:
    # name: kafka-ca-issuer
    name: selfsigned-bootstrap
    # kind: Issuer
    kind: ClusterIssuer
---