---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cluster-tls-cert
  namespace: strimzi-kafka
spec:
  secretName: kafka-cluster-tls-cert
  subject:
    organizations:
    - ifougali
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - kafka-listener.pfs.pack
  - kafka-boostrap.pfs.pack
  - kafka-broker-0.pfs.pack
  - kafka-broker-1.pfs.pack
  - kafka-broker-2.pfs.pack
  issuerRef:
    name: kafka-cert-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kafka-cert-issuer
  namespace: strimzi-kafka
spec:
  selfSigned: {}
