apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ifoughali
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: ifoughali
          key: password
  # authorization:
  #   type: simple
  #   acls:
  #   - resource:
  #       type: topic
  #       name: '*'
  #       patternType: literal
  #     operation: All
  authorization:
    type: simple
    acls:
      - type: allow
        resource:
          type: topic
          name: "*"
        operations:
        - All

  #   - resource:
  #       type: topic
  #       name: "*"
  #       patternType: literal
  #     operations:
  #     - 'All'
  #     host: "*"
  #   - resource:
  #       type: group
  #       name: "*"
  #       patternType: literal
  #     operations:
  #     - 'All'
  #     host: "*"
  #   - resource:
  #       type: cluster
  #     operations:
  #     - 'All'
  #   - resource:
  #       type: transactionalId
  #       name: "*"
  #       patternType: literal
  #     operations:
  #     - 'All'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-ui
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-ui
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: "*"
        patternType: literal
      operations:
      - 'All'
      host: "*"
    - resource:
        type: group
        name: "*"
        patternType: literal
      operations:
      - 'All'
      host: "*"
    - resource:
        type: cluster
      operations:
      - 'All'
    - resource:
        type: transactionalId
        name: "*"
        patternType: literal
      operations:
      - 'All'
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    # producerByteRate: 1048576 # (1)
    # consumerByteRate: 2097152 # (2)
    # requestPercentage: 55 # (3)
    # controllerMutationRate: 10 # (4)
#     Byte-per-second quota on the amount of data the user can push to a Kafka broker.

# Byte-per-second quota on the amount of data the user can fetch from a Kafka broker.

# CPU utilization limit as a percentage of time for a client group.

# Number of concurrent partition creation and deletion operations (mutations) allowed per second.
  partitions: 12
  replicas: 3
