replicas: 3

watchNamespaces:
- strimzi-kafka

dashboards:
  enabled: true
  namespace: ~
  label: grafana_dashboard # this is the default value from the grafana chart
  labelValue: "1" # this is the default value from the grafana chart
  annotations: {}
  extraLabels: {}
