apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-proxy-env
spec:
  rules:
    - name: add-proxy-env-vars
      match:
        resources:
          kinds:
            - Pod
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    env:
                      - name: HTTP_PROXY
                        value: "http://10.66.8.162:3128"
                      - name: HTTPS_PROXY
                        value: "http://10.66.8.162:3128"
                      - name: NO_PROXY
                        value: "lorioncp01vel,lorioncp02vel,lorioncp03vel,localhost,::1,127.0.0.1,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,.lab,.sfr.com,.pack,.prod"
