apiVersion: v1
kind: Service
metadata:
  name: "cert-manager-webhook"
  namespace: cert-manager
  # annotations:
  #   service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: ExternalName
  externalName: "cert-manager-webhook.cert-manager.svc.cluster.local"
  # externalName: my.database.example.com
