apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-kafka
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "xfs"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  defaultDisksConfig: '[ { "path":"/var/lib/longhorn", "allowScheduling":true }]'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
